# Generated by Django 6.0.4 on 2026-04-26 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='clauses_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='compliance_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='compliance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='fraud_analysis_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='fraud_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='key_data_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='risk_analysis_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GeneratedClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
